### PR TITLE
ParquetJS Memory Issue

### PR DESCRIPTION
**Pull request by arnabguptadev**
This is a fix for issue 60 (https://github.com/ironSource/parquetjs/issues/60) and 101 (https://github.com/ironSource/parquetjs/issues/101)

### CODE REVIEW

**Comment by arnabguptadev** [comment]
Please check if this works. I retained the change in the test file to force the issue of unordered write and make sure it works.

**Comment by arnabguptadev** [comment]
@asmuth  - Will it be possible to get a review of this pull request this week and then a merge? Thanks!

**Comment by asmuth** [comment]
Code looks good to me and tests still pass; will go ahead and merge this since there seem to be no objections. Thank you!

**Comment by arnabguptadev** [comment]
Thank you @asmuth. This is very helpful.

**Comment by arnabguptadev** [comment]
@asmuth - will it be possible to get an npm build, or does this have to wait to be made along with other changes?

**Comment by dobesv** [comment]
Although I see the solution here is merged, it doesn't seem the best.  Probably instead of a mutex you could just have a variable on the writer that is the promise of the current row group being written and await that if it is there, e.g.

```
appendRow() {
  if(this.writeInProgress) await this.writeInProgress;

// ...

if (this.rowBuffer.rowCount >= this.rowGroupSize) {
        this.writeInProgress = this.envelopeWriter.writeRowGroup(this.rowBuffer);
        this.rowBuffer = {};
        await this.writeInProgress;
        this.writeInProgress = null;
      }
}


close() {
  if(this.writeInProgress) await this.writeInProgress;
}
```

Can avoid an extra dependency that way.

**Pull request merged**
